id: P000293
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1017144
  title: མཁས་གྲུབ་སྦྱིན་པ་དར་རྒྱས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    5599992288814facb883210d9ebd9e8a:
      image_group_id: I00EGS1017146
      title: Volume 1 of
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
